### ISSUE TITLE
DefaultMessage should have a composite key

### ISSUE THREAD

**Issue by patolax** [VirgilSecurity/demo-firebase-android#2]
https://github.com/VirgilSecurity/demo-firebase-android/blob/master/app/src/main/java/com/android/virgilsecurity/virgilonfire/data/model/DefaultMessage.java

this file above needs to use @Entity(primaryKeys= {"messageId", "channel_id" }) I think.

**Comment by BavovnaIsTaken** [comment]
Hi, @tpatikirikorala !
Yes, it's a good idea to use channel_id as primary key too, because we querying messages via channel id frequently. It will reduce the query time significantly for large amounts of data.

**Comment by patolax** [comment]
yes, but when messageId is the only primary key, how does messages with same ids on different channels be inserted to the roomdb. Its a bug, isn't it?

**Comment by BavovnaIsTaken** [comment]
Yes, you're right. To have unique primary key we need to use composite primary key as you specified with both "messageId" and "channel_id". 
But it's weird why room lets to save rows with non-unique primary key. Seems that it happens because of "OnConflictStrategy.IGNORE" in MessageDao, but on the other hand this shouldn't work for two users on the same device while it's actually do work.
Anyway thanks for noticing this.

**Comment by BavovnaIsTaken** [comment]
Can you confirm that it works well now in 'dev' branch? If so - I will close the issue.
(By the way did you have any issues because of that non-composite primary key?)

**Comment by patolax** [comment]
yes, I faced the issue and realized composite key is the solution after debugging.
